Header header

bool                isAuto        
bool                isEstop       
bool                isForward        
bool                isBackward
float64             speed       # m/s      
float64             steer       # radian
uint8               brake       # 0 ~ 100 %       
int32               encoder     # raw encoder value     
uint8               alive       # increases at each step    
